Capstone day three
mstanley-me/StanleyCapstone pull request #3
Opened 2022-02-09 18:51 UTC by mstanley-me

# In this Milestone i've:

 - made the features speakers section
 - made it easier to use on mobile
 - added image of speakers
 - Added some modification on css file

# Technology use:

 - HTML
 - CSS
 - JavaScript
 - Linters
 - Git/GitHub

Thanks for your review 😁!

2022-02-09 20:33 UTC, Amrhub reviewed
Hi @mstanley-me, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that your project is not meeting all requirements. 
You are supposed to make the pull request after you finish the entire Capstone project requirements 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-02-11 08:33 UTC, Kingstalux requested changes
Hi @mstanley-me , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._
- [ ] In the video presentation, you are supposed to show us your complete project on both desktop and mobile screens and then talk about a piece of interesting code you worked on. Please record the presentation again and make sure that you provide all the necessary information.
- [ ] Also your project has not been deployed well, please make sure you provide the correct link to the live demo of your project to make your README  more professional.

You can use as many of my optional suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-11 08:33 UTC, Kingstalux commented on index.html
> +        </section>
- [ ] Good job following the design specifications 👍 but you'll notice that in the desktop version, the speaker images on the right-hand side are larger than those on the left-hand side. It would be great if you could address this issue.
- Your design:
![Capture9](https://user-images.githubusercontent.com/85113567/153556990-534e0468-4113-4e7e-b709-caf682f0a300.PNG)
- [ ] Also in the mobile version only 2 speakers should be displayed which you have done well 💯 but when a user clicks on the `More` button, the rest of the speakers should be displayed. It would be great if you could add that functionality.
- [ ] Also the margin under your `More` button is too large, it would be great if you could reduce that too.
- Your design:
![Capture5](https://user-images.githubusercontent.com/85113567/153557210-fa5018d3-b799-438f-9092-eae9afa6fc39.PNG)
- Required design:

![Capture6](https://user-images.githubusercontent.com/85113567/153557234-d452fe3b-7e8b-447e-a138-b20d6695a2f2.PNG)

2022-02-11 08:33 UTC, Kingstalux commented on about.html
> +                <li class="item"><a href="#">CC Campaign</a></li>
- [ ] Nice job styling the navbar 👍 but you'll notice that the `CC Campaign` button should be colored on both pages. Do well to rectify this.
- Your design:
![Capture7](https://user-images.githubusercontent.com/85113567/153557937-e78fa1bf-9476-4565-978f-a24c5bfb9fe2.PNG)
- Required design:
![Capture8](https://user-images.githubusercontent.com/85113567/153558010-8ce6d887-a397-4813-89a6-a64580190d4a.PNG)

2022-02-11 08:33 UTC, Kingstalux commented on about.html
> +                    <h4 class="h-content">"XDev Announcement!"</h4>
- [ ] Since this is the main heading of your page, it would be better to use an `h1` tag for best semantic practices.

2022-02-11 08:33 UTC, Kingstalux commented on about.html
> +                </div>
- [ ] It would be great if you could add some margin-top and bottom to your partner's section so that it could look better and more like the design.
- Your design
![C1](https://user-images.githubusercontent.com/85113567/153558660-ece0768d-f43a-4eaa-aaa5-863cd050d990.PNG)
- Required design:
![Capture2](https://user-images.githubusercontent.com/85113567/153558740-0e3ff555-b9a8-40b9-9884-b16cc67966c0.PNG)

2022-02-11 17:18 UTC, Lordkaito approved these changes
Hi @mstanley-me, 

<img src="https://media.giphy.com/media/3oz8xVjxTPNEzyKRKU/giphy.gif" width="250px" height="200px">

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 

- [ ] [OPTIONAL] If you take a look at your mobile version when you navigate to the about page and click on the hamburger menu, there is no way to go back to the home page using this menu. It would be nice if you add a link to navigate to the home page from this menu as well!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-02-11 17:56 UTC, mstanley-me commented
Thank you so much guys!

On Fri, 11 Feb 2022 at 18:18, Isaí Céspedes Sánchez <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @mstanley-me <https://github.com/mstanley-me>,
>
>
> <https://camo.githubusercontent.com/bf946cf27d51f6f72da69dd09891ff56c0234eff56609996636639eaeb623a73/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f7a3878566a7854504e457a794b524b552f67697068792e676966>
>
> In my opinion, your project is ready for presentation! There is nothing
> else to say other than... it's time to merge it [image: :shipit:]
>
> Good luck! 🎉
>
>    - [OPTIONAL] If you take a look at your mobile version when you
>    navigate to the about page and click on the hamburger menu, there is no way
>    to go back to the home page using this menu. It would be nice if you add a
>    link to navigate to the home page from this menu as well!
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mstanley-me/StanleyCapstone/pull/3#pullrequestreview-880466207>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVYCZFJHMWBKVCZ6QF5SUE3U2VAFPANCNFSM5N6LDOZA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-11 18:16 UTC, merged